// Generated by CoffeeScript 1.7.1

/*
	Copyright 2012-2014 David Pearson.
	All rights reserved.
 */

(function() {
  var child_process, runCmd, runSilent;

  child_process = require("child_process");

  runCmd = function(cmd, args, cb) {
    var opts, proc;
    opts = {
      stdio: "inherit",
      stderr: "inherit"
    };
    proc = child_process.spawn(cmd, args, opts);
    if (cb != null) {
      return proc.on("close", cb);
    }
  };

  runSilent = function(cmd, args, cb) {
    var opts, proc;
    opts = {
      stdio: "ignore",
      stderr: "ignore"
    };
    proc = child_process.spawn(cmd, args, opts);
    if (cb != null) {
      return proc.on("close", cb);
    }
  };

  exports.runCmd = runCmd;

  exports.runSilent = runSilent;

}).call(this);
